export class Product {
    productID:number;
    productName:string;
    price:number;
    discount:string;
    imageUrl:string;
    productDescription:string;
    quantity:number;
    ImageFile:null;
    ImageName:string;
    category:string;
    isSlider:boolean;
    isCategory:boolean;
    isLatestProduct:boolean;
    isBestProduct:boolean;
    isBestCollection:boolean;
    isLatestOffer:boolean;
    isgallery:boolean;
    isAddedToCart:boolean;
    isAddedToCheckout:boolean;
    inConfirmation:boolean;
    totalPrice=0;
}
